services:
  mcp-app-server:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - mcp-app-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  mcp-app-network:
    driver: bridge
